/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppModelosRouteImport } from './routes/_app.modelos'
import { Route as AppLixeiraRouteImport } from './routes/_app.lixeira'
import { Route as AppIntegracoesRouteImport } from './routes/_app.integracoes'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppEquipaRouteImport } from './routes/_app.equipa'
import { Route as AppDefinicoesGeraisRouteImport } from './routes/_app.definicoes-gerais'
import { Route as AppDefinicoesRouteImport } from './routes/_app.definicoes'
import { Route as AppCaixaDeEntradaRouteImport } from './routes/_app.caixa-de-entrada'
import { Route as AppBibliotecaRouteImport } from './routes/_app.biblioteca'
import { Route as AppBaseJuridicaRouteImport } from './routes/_app.base-juridica'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppSessoesIndexRouteImport } from './routes/_app.sessoes.index'
import { Route as AppDossiesIndexRouteImport } from './routes/_app.dossies.index'
import { Route as AppAssuntosIndexRouteImport } from './routes/_app.assuntos.index'
import { Route as AppAssembleiasIndexRouteImport } from './routes/_app.assembleias.index'
import { Route as AppSessoesIdRouteImport } from './routes/_app.sessoes.$id'
import { Route as AppDossiesDossieIdRouteImport } from './routes/_app.dossies.$dossieId'
import { Route as AppDocumentosDocumentoIdRouteImport } from './routes/_app.documentos.$documentoId'
import { Route as AppAssuntosDossieIdRouteImport } from './routes/_app.assuntos.$dossieId'
import { Route as AppAssembleiasIdRouteImport } from './routes/_app.assembleias.$id'
import { Route as AppAssuntosDossieIdIndexRouteImport } from './routes/_app.assuntos.$dossieId.index'
import { Route as AppSessoesIdPreparacaoRouteImport } from './routes/_app.sessoes.$id.preparacao'
import { Route as AppBibliotecaDocumentosDocIdRouteImport } from './routes/_app.biblioteca.documentos.$docId'
import { Route as AppAssembleiasIdPreparacaoRouteImport } from './routes/_app.assembleias.$id.preparacao'
import { Route as AppSessoesIdPreparacaoPontosRouteImport } from './routes/_app.sessoes.$id.preparacao.pontos'
import { Route as AppSessoesIdPreparacaoEstrategiaRouteImport } from './routes/_app.sessoes.$id.preparacao.estrategia'
import { Route as AppSessoesIdPreparacaoDocumentosACriarRouteImport } from './routes/_app.sessoes.$id.preparacao.documentos-a-criar'
import { Route as AppSessoesIdPreparacaoDocumentosRouteImport } from './routes/_app.sessoes.$id.preparacao.documentos'
import { Route as AppSessoesIdDocumentosDocIdRouteImport } from './routes/_app.sessoes.$id.documentos.$docId'
import { Route as AppDossiesDossieIdDocumentosDocumentoIdRouteImport } from './routes/_app.dossies.$dossieId.documentos.$documentoId'
import { Route as AppAssuntosDossieIdDocumentosDocumentoIdRouteImport } from './routes/_app.assuntos.$dossieId.documentos.$documentoId'
import { Route as AppAssembleiasIdPreparacaoPontosRouteImport } from './routes/_app.assembleias.$id.preparacao.pontos'
import { Route as AppAssembleiasIdPreparacaoEstrategiaRouteImport } from './routes/_app.assembleias.$id.preparacao.estrategia'
import { Route as AppAssembleiasIdPreparacaoDocumentosACriarRouteImport } from './routes/_app.assembleias.$id.preparacao.documentos-a-criar'
import { Route as AppAssembleiasIdPreparacaoDocumentosRouteImport } from './routes/_app.assembleias.$id.preparacao.documentos'
import { Route as AppAssembleiasIdDocumentosDocIdRouteImport } from './routes/_app.assembleias.$id.documentos.$docId'
import { Route as AppSessoesIdPreparacaoPontosPontoIdRouteImport } from './routes/_app.sessoes.$id.preparacao.pontos.$pontoId'
import { Route as AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRouteImport } from './routes/_app.sessoes.$id.preparacao.documentos-a-criar.$rascunhoId'
import { Route as AppAssembleiasIdPreparacaoPontosPontoIdRouteImport } from './routes/_app.assembleias.$id.preparacao.pontos.$pontoId'
import { Route as AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRouteImport } from './routes/_app.assembleias.$id.preparacao.documentos-a-criar.$rascunhoId'
import { Route as AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRouteImport } from './routes/_app.sessoes.$id.preparacao.pontos.$pontoId.rascunhos.$rascunhoId'
import { Route as AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRouteImport } from './routes/_app.assembleias.$id.preparacao.pontos.$pontoId.rascunhos.$rascunhoId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppModelosRoute = AppModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AppRoute,
} as any)
const AppLixeiraRoute = AppLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipaRoute = AppEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => AppRoute,
} as any)
const AppDefinicoesGeraisRoute = AppDefinicoesGeraisRouteImport.update({
  id: '/definicoes-gerais',
  path: '/definicoes-gerais',
  getParentRoute: () => AppRoute,
} as any)
const AppDefinicoesRoute = AppDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCaixaDeEntradaRoute = AppCaixaDeEntradaRouteImport.update({
  id: '/caixa-de-entrada',
  path: '/caixa-de-entrada',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppBaseJuridicaRoute = AppBaseJuridicaRouteImport.update({
  id: '/base-juridica',
  path: '/base-juridica',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppSessoesIndexRoute = AppSessoesIndexRouteImport.update({
  id: '/sessoes/',
  path: '/sessoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppDossiesIndexRoute = AppDossiesIndexRouteImport.update({
  id: '/dossies/',
  path: '/dossies/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssuntosIndexRoute = AppAssuntosIndexRouteImport.update({
  id: '/assuntos/',
  path: '/assuntos/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssembleiasIndexRoute = AppAssembleiasIndexRouteImport.update({
  id: '/assembleias/',
  path: '/assembleias/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessoesIdRoute = AppSessoesIdRouteImport.update({
  id: '/sessoes/$id',
  path: '/sessoes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDossiesDossieIdRoute = AppDossiesDossieIdRouteImport.update({
  id: '/dossies/$dossieId',
  path: '/dossies/$dossieId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosDocumentoIdRoute =
  AppDocumentosDocumentoIdRouteImport.update({
    id: '/documentos/$documentoId',
    path: '/documentos/$documentoId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAssuntosDossieIdRoute = AppAssuntosDossieIdRouteImport.update({
  id: '/assuntos/$dossieId',
  path: '/assuntos/$dossieId',
  getParentRoute: () => AppRoute,
} as any)
const AppAssembleiasIdRoute = AppAssembleiasIdRouteImport.update({
  id: '/assembleias/$id',
  path: '/assembleias/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssuntosDossieIdIndexRoute =
  AppAssuntosDossieIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAssuntosDossieIdRoute,
  } as any)
const AppSessoesIdPreparacaoRoute = AppSessoesIdPreparacaoRouteImport.update({
  id: '/preparacao',
  path: '/preparacao',
  getParentRoute: () => AppSessoesIdRoute,
} as any)
const AppBibliotecaDocumentosDocIdRoute =
  AppBibliotecaDocumentosDocIdRouteImport.update({
    id: '/documentos/$docId',
    path: '/documentos/$docId',
    getParentRoute: () => AppBibliotecaRoute,
  } as any)
const AppAssembleiasIdPreparacaoRoute =
  AppAssembleiasIdPreparacaoRouteImport.update({
    id: '/preparacao',
    path: '/preparacao',
    getParentRoute: () => AppAssembleiasIdRoute,
  } as any)
const AppSessoesIdPreparacaoPontosRoute =
  AppSessoesIdPreparacaoPontosRouteImport.update({
    id: '/pontos',
    path: '/pontos',
    getParentRoute: () => AppSessoesIdPreparacaoRoute,
  } as any)
const AppSessoesIdPreparacaoEstrategiaRoute =
  AppSessoesIdPreparacaoEstrategiaRouteImport.update({
    id: '/estrategia',
    path: '/estrategia',
    getParentRoute: () => AppSessoesIdPreparacaoRoute,
  } as any)
const AppSessoesIdPreparacaoDocumentosACriarRoute =
  AppSessoesIdPreparacaoDocumentosACriarRouteImport.update({
    id: '/documentos-a-criar',
    path: '/documentos-a-criar',
    getParentRoute: () => AppSessoesIdPreparacaoRoute,
  } as any)
const AppSessoesIdPreparacaoDocumentosRoute =
  AppSessoesIdPreparacaoDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AppSessoesIdPreparacaoRoute,
  } as any)
const AppSessoesIdDocumentosDocIdRoute =
  AppSessoesIdDocumentosDocIdRouteImport.update({
    id: '/documentos/$docId',
    path: '/documentos/$docId',
    getParentRoute: () => AppSessoesIdRoute,
  } as any)
const AppDossiesDossieIdDocumentosDocumentoIdRoute =
  AppDossiesDossieIdDocumentosDocumentoIdRouteImport.update({
    id: '/documentos/$documentoId',
    path: '/documentos/$documentoId',
    getParentRoute: () => AppDossiesDossieIdRoute,
  } as any)
const AppAssuntosDossieIdDocumentosDocumentoIdRoute =
  AppAssuntosDossieIdDocumentosDocumentoIdRouteImport.update({
    id: '/documentos/$documentoId',
    path: '/documentos/$documentoId',
    getParentRoute: () => AppAssuntosDossieIdRoute,
  } as any)
const AppAssembleiasIdPreparacaoPontosRoute =
  AppAssembleiasIdPreparacaoPontosRouteImport.update({
    id: '/pontos',
    path: '/pontos',
    getParentRoute: () => AppAssembleiasIdPreparacaoRoute,
  } as any)
const AppAssembleiasIdPreparacaoEstrategiaRoute =
  AppAssembleiasIdPreparacaoEstrategiaRouteImport.update({
    id: '/estrategia',
    path: '/estrategia',
    getParentRoute: () => AppAssembleiasIdPreparacaoRoute,
  } as any)
const AppAssembleiasIdPreparacaoDocumentosACriarRoute =
  AppAssembleiasIdPreparacaoDocumentosACriarRouteImport.update({
    id: '/documentos-a-criar',
    path: '/documentos-a-criar',
    getParentRoute: () => AppAssembleiasIdPreparacaoRoute,
  } as any)
const AppAssembleiasIdPreparacaoDocumentosRoute =
  AppAssembleiasIdPreparacaoDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AppAssembleiasIdPreparacaoRoute,
  } as any)
const AppAssembleiasIdDocumentosDocIdRoute =
  AppAssembleiasIdDocumentosDocIdRouteImport.update({
    id: '/documentos/$docId',
    path: '/documentos/$docId',
    getParentRoute: () => AppAssembleiasIdRoute,
  } as any)
const AppSessoesIdPreparacaoPontosPontoIdRoute =
  AppSessoesIdPreparacaoPontosPontoIdRouteImport.update({
    id: '/$pontoId',
    path: '/$pontoId',
    getParentRoute: () => AppSessoesIdPreparacaoPontosRoute,
  } as any)
const AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRoute =
  AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRouteImport.update({
    id: '/$rascunhoId',
    path: '/$rascunhoId',
    getParentRoute: () => AppSessoesIdPreparacaoDocumentosACriarRoute,
  } as any)
const AppAssembleiasIdPreparacaoPontosPontoIdRoute =
  AppAssembleiasIdPreparacaoPontosPontoIdRouteImport.update({
    id: '/$pontoId',
    path: '/$pontoId',
    getParentRoute: () => AppAssembleiasIdPreparacaoPontosRoute,
  } as any)
const AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRoute =
  AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRouteImport.update({
    id: '/$rascunhoId',
    path: '/$rascunhoId',
    getParentRoute: () => AppAssembleiasIdPreparacaoDocumentosACriarRoute,
  } as any)
const AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute =
  AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRouteImport.update({
    id: '/rascunhos/$rascunhoId',
    path: '/rascunhos/$rascunhoId',
    getParentRoute: () => AppSessoesIdPreparacaoPontosPontoIdRoute,
  } as any)
const AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute =
  AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRouteImport.update({
    id: '/rascunhos/$rascunhoId',
    path: '/rascunhos/$rascunhoId',
    getParentRoute: () => AppAssembleiasIdPreparacaoPontosPontoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/base-juridica': typeof AppBaseJuridicaRoute
  '/biblioteca': typeof AppBibliotecaRouteWithChildren
  '/caixa-de-entrada': typeof AppCaixaDeEntradaRoute
  '/definicoes': typeof AppDefinicoesRoute
  '/definicoes-gerais': typeof AppDefinicoesGeraisRoute
  '/equipa': typeof AppEquipaRoute
  '/historico': typeof AppHistoricoRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/lixeira': typeof AppLixeiraRoute
  '/modelos': typeof AppModelosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/assembleias/$id': typeof AppAssembleiasIdRouteWithChildren
  '/assuntos/$dossieId': typeof AppAssuntosDossieIdRouteWithChildren
  '/documentos/$documentoId': typeof AppDocumentosDocumentoIdRoute
  '/dossies/$dossieId': typeof AppDossiesDossieIdRouteWithChildren
  '/sessoes/$id': typeof AppSessoesIdRouteWithChildren
  '/assembleias/': typeof AppAssembleiasIndexRoute
  '/assuntos/': typeof AppAssuntosIndexRoute
  '/dossies/': typeof AppDossiesIndexRoute
  '/sessoes/': typeof AppSessoesIndexRoute
  '/assembleias/$id/preparacao': typeof AppAssembleiasIdPreparacaoRouteWithChildren
  '/biblioteca/documentos/$docId': typeof AppBibliotecaDocumentosDocIdRoute
  '/sessoes/$id/preparacao': typeof AppSessoesIdPreparacaoRouteWithChildren
  '/assuntos/$dossieId/': typeof AppAssuntosDossieIdIndexRoute
  '/assembleias/$id/documentos/$docId': typeof AppAssembleiasIdDocumentosDocIdRoute
  '/assembleias/$id/preparacao/documentos': typeof AppAssembleiasIdPreparacaoDocumentosRoute
  '/assembleias/$id/preparacao/documentos-a-criar': typeof AppAssembleiasIdPreparacaoDocumentosACriarRouteWithChildren
  '/assembleias/$id/preparacao/estrategia': typeof AppAssembleiasIdPreparacaoEstrategiaRoute
  '/assembleias/$id/preparacao/pontos': typeof AppAssembleiasIdPreparacaoPontosRouteWithChildren
  '/assuntos/$dossieId/documentos/$documentoId': typeof AppAssuntosDossieIdDocumentosDocumentoIdRoute
  '/dossies/$dossieId/documentos/$documentoId': typeof AppDossiesDossieIdDocumentosDocumentoIdRoute
  '/sessoes/$id/documentos/$docId': typeof AppSessoesIdDocumentosDocIdRoute
  '/sessoes/$id/preparacao/documentos': typeof AppSessoesIdPreparacaoDocumentosRoute
  '/sessoes/$id/preparacao/documentos-a-criar': typeof AppSessoesIdPreparacaoDocumentosACriarRouteWithChildren
  '/sessoes/$id/preparacao/estrategia': typeof AppSessoesIdPreparacaoEstrategiaRoute
  '/sessoes/$id/preparacao/pontos': typeof AppSessoesIdPreparacaoPontosRouteWithChildren
  '/assembleias/$id/preparacao/documentos-a-criar/$rascunhoId': typeof AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRoute
  '/assembleias/$id/preparacao/pontos/$pontoId': typeof AppAssembleiasIdPreparacaoPontosPontoIdRouteWithChildren
  '/sessoes/$id/preparacao/documentos-a-criar/$rascunhoId': typeof AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRoute
  '/sessoes/$id/preparacao/pontos/$pontoId': typeof AppSessoesIdPreparacaoPontosPontoIdRouteWithChildren
  '/assembleias/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId': typeof AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute
  '/sessoes/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId': typeof AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute
}
export interface FileRoutesByTo {
  '/completar-perfil': typeof CompletarPerfilRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/base-juridica': typeof AppBaseJuridicaRoute
  '/biblioteca': typeof AppBibliotecaRouteWithChildren
  '/caixa-de-entrada': typeof AppCaixaDeEntradaRoute
  '/definicoes': typeof AppDefinicoesRoute
  '/definicoes-gerais': typeof AppDefinicoesGeraisRoute
  '/equipa': typeof AppEquipaRoute
  '/historico': typeof AppHistoricoRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/lixeira': typeof AppLixeiraRoute
  '/modelos': typeof AppModelosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/': typeof AppIndexRoute
  '/assembleias/$id': typeof AppAssembleiasIdRouteWithChildren
  '/documentos/$documentoId': typeof AppDocumentosDocumentoIdRoute
  '/dossies/$dossieId': typeof AppDossiesDossieIdRouteWithChildren
  '/sessoes/$id': typeof AppSessoesIdRouteWithChildren
  '/assembleias': typeof AppAssembleiasIndexRoute
  '/assuntos': typeof AppAssuntosIndexRoute
  '/dossies': typeof AppDossiesIndexRoute
  '/sessoes': typeof AppSessoesIndexRoute
  '/assembleias/$id/preparacao': typeof AppAssembleiasIdPreparacaoRouteWithChildren
  '/biblioteca/documentos/$docId': typeof AppBibliotecaDocumentosDocIdRoute
  '/sessoes/$id/preparacao': typeof AppSessoesIdPreparacaoRouteWithChildren
  '/assuntos/$dossieId': typeof AppAssuntosDossieIdIndexRoute
  '/assembleias/$id/documentos/$docId': typeof AppAssembleiasIdDocumentosDocIdRoute
  '/assembleias/$id/preparacao/documentos': typeof AppAssembleiasIdPreparacaoDocumentosRoute
  '/assembleias/$id/preparacao/documentos-a-criar': typeof AppAssembleiasIdPreparacaoDocumentosACriarRouteWithChildren
  '/assembleias/$id/preparacao/estrategia': typeof AppAssembleiasIdPreparacaoEstrategiaRoute
  '/assembleias/$id/preparacao/pontos': typeof AppAssembleiasIdPreparacaoPontosRouteWithChildren
  '/assuntos/$dossieId/documentos/$documentoId': typeof AppAssuntosDossieIdDocumentosDocumentoIdRoute
  '/dossies/$dossieId/documentos/$documentoId': typeof AppDossiesDossieIdDocumentosDocumentoIdRoute
  '/sessoes/$id/documentos/$docId': typeof AppSessoesIdDocumentosDocIdRoute
  '/sessoes/$id/preparacao/documentos': typeof AppSessoesIdPreparacaoDocumentosRoute
  '/sessoes/$id/preparacao/documentos-a-criar': typeof AppSessoesIdPreparacaoDocumentosACriarRouteWithChildren
  '/sessoes/$id/preparacao/estrategia': typeof AppSessoesIdPreparacaoEstrategiaRoute
  '/sessoes/$id/preparacao/pontos': typeof AppSessoesIdPreparacaoPontosRouteWithChildren
  '/assembleias/$id/preparacao/documentos-a-criar/$rascunhoId': typeof AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRoute
  '/assembleias/$id/preparacao/pontos/$pontoId': typeof AppAssembleiasIdPreparacaoPontosPontoIdRouteWithChildren
  '/sessoes/$id/preparacao/documentos-a-criar/$rascunhoId': typeof AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRoute
  '/sessoes/$id/preparacao/pontos/$pontoId': typeof AppSessoesIdPreparacaoPontosPontoIdRouteWithChildren
  '/assembleias/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId': typeof AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute
  '/sessoes/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId': typeof AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/completar-perfil': typeof CompletarPerfilRoute
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/base-juridica': typeof AppBaseJuridicaRoute
  '/_app/biblioteca': typeof AppBibliotecaRouteWithChildren
  '/_app/caixa-de-entrada': typeof AppCaixaDeEntradaRoute
  '/_app/definicoes': typeof AppDefinicoesRoute
  '/_app/definicoes-gerais': typeof AppDefinicoesGeraisRoute
  '/_app/equipa': typeof AppEquipaRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/integracoes': typeof AppIntegracoesRoute
  '/_app/lixeira': typeof AppLixeiraRoute
  '/_app/modelos': typeof AppModelosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assembleias/$id': typeof AppAssembleiasIdRouteWithChildren
  '/_app/assuntos/$dossieId': typeof AppAssuntosDossieIdRouteWithChildren
  '/_app/documentos/$documentoId': typeof AppDocumentosDocumentoIdRoute
  '/_app/dossies/$dossieId': typeof AppDossiesDossieIdRouteWithChildren
  '/_app/sessoes/$id': typeof AppSessoesIdRouteWithChildren
  '/_app/assembleias/': typeof AppAssembleiasIndexRoute
  '/_app/assuntos/': typeof AppAssuntosIndexRoute
  '/_app/dossies/': typeof AppDossiesIndexRoute
  '/_app/sessoes/': typeof AppSessoesIndexRoute
  '/_app/assembleias/$id/preparacao': typeof AppAssembleiasIdPreparacaoRouteWithChildren
  '/_app/biblioteca/documentos/$docId': typeof AppBibliotecaDocumentosDocIdRoute
  '/_app/sessoes/$id/preparacao': typeof AppSessoesIdPreparacaoRouteWithChildren
  '/_app/assuntos/$dossieId/': typeof AppAssuntosDossieIdIndexRoute
  '/_app/assembleias/$id/documentos/$docId': typeof AppAssembleiasIdDocumentosDocIdRoute
  '/_app/assembleias/$id/preparacao/documentos': typeof AppAssembleiasIdPreparacaoDocumentosRoute
  '/_app/assembleias/$id/preparacao/documentos-a-criar': typeof AppAssembleiasIdPreparacaoDocumentosACriarRouteWithChildren
  '/_app/assembleias/$id/preparacao/estrategia': typeof AppAssembleiasIdPreparacaoEstrategiaRoute
  '/_app/assembleias/$id/preparacao/pontos': typeof AppAssembleiasIdPreparacaoPontosRouteWithChildren
  '/_app/assuntos/$dossieId/documentos/$documentoId': typeof AppAssuntosDossieIdDocumentosDocumentoIdRoute
  '/_app/dossies/$dossieId/documentos/$documentoId': typeof AppDossiesDossieIdDocumentosDocumentoIdRoute
  '/_app/sessoes/$id/documentos/$docId': typeof AppSessoesIdDocumentosDocIdRoute
  '/_app/sessoes/$id/preparacao/documentos': typeof AppSessoesIdPreparacaoDocumentosRoute
  '/_app/sessoes/$id/preparacao/documentos-a-criar': typeof AppSessoesIdPreparacaoDocumentosACriarRouteWithChildren
  '/_app/sessoes/$id/preparacao/estrategia': typeof AppSessoesIdPreparacaoEstrategiaRoute
  '/_app/sessoes/$id/preparacao/pontos': typeof AppSessoesIdPreparacaoPontosRouteWithChildren
  '/_app/assembleias/$id/preparacao/documentos-a-criar/$rascunhoId': typeof AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRoute
  '/_app/assembleias/$id/preparacao/pontos/$pontoId': typeof AppAssembleiasIdPreparacaoPontosPontoIdRouteWithChildren
  '/_app/sessoes/$id/preparacao/documentos-a-criar/$rascunhoId': typeof AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRoute
  '/_app/sessoes/$id/preparacao/pontos/$pontoId': typeof AppSessoesIdPreparacaoPontosPontoIdRouteWithChildren
  '/_app/assembleias/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId': typeof AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute
  '/_app/sessoes/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId': typeof AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completar-perfil'
    | '/login'
    | '/agenda'
    | '/base-juridica'
    | '/biblioteca'
    | '/caixa-de-entrada'
    | '/definicoes'
    | '/definicoes-gerais'
    | '/equipa'
    | '/historico'
    | '/integracoes'
    | '/lixeira'
    | '/modelos'
    | '/relatorios'
    | '/assembleias/$id'
    | '/assuntos/$dossieId'
    | '/documentos/$documentoId'
    | '/dossies/$dossieId'
    | '/sessoes/$id'
    | '/assembleias/'
    | '/assuntos/'
    | '/dossies/'
    | '/sessoes/'
    | '/assembleias/$id/preparacao'
    | '/biblioteca/documentos/$docId'
    | '/sessoes/$id/preparacao'
    | '/assuntos/$dossieId/'
    | '/assembleias/$id/documentos/$docId'
    | '/assembleias/$id/preparacao/documentos'
    | '/assembleias/$id/preparacao/documentos-a-criar'
    | '/assembleias/$id/preparacao/estrategia'
    | '/assembleias/$id/preparacao/pontos'
    | '/assuntos/$dossieId/documentos/$documentoId'
    | '/dossies/$dossieId/documentos/$documentoId'
    | '/sessoes/$id/documentos/$docId'
    | '/sessoes/$id/preparacao/documentos'
    | '/sessoes/$id/preparacao/documentos-a-criar'
    | '/sessoes/$id/preparacao/estrategia'
    | '/sessoes/$id/preparacao/pontos'
    | '/assembleias/$id/preparacao/documentos-a-criar/$rascunhoId'
    | '/assembleias/$id/preparacao/pontos/$pontoId'
    | '/sessoes/$id/preparacao/documentos-a-criar/$rascunhoId'
    | '/sessoes/$id/preparacao/pontos/$pontoId'
    | '/assembleias/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
    | '/sessoes/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/completar-perfil'
    | '/login'
    | '/agenda'
    | '/base-juridica'
    | '/biblioteca'
    | '/caixa-de-entrada'
    | '/definicoes'
    | '/definicoes-gerais'
    | '/equipa'
    | '/historico'
    | '/integracoes'
    | '/lixeira'
    | '/modelos'
    | '/relatorios'
    | '/'
    | '/assembleias/$id'
    | '/documentos/$documentoId'
    | '/dossies/$dossieId'
    | '/sessoes/$id'
    | '/assembleias'
    | '/assuntos'
    | '/dossies'
    | '/sessoes'
    | '/assembleias/$id/preparacao'
    | '/biblioteca/documentos/$docId'
    | '/sessoes/$id/preparacao'
    | '/assuntos/$dossieId'
    | '/assembleias/$id/documentos/$docId'
    | '/assembleias/$id/preparacao/documentos'
    | '/assembleias/$id/preparacao/documentos-a-criar'
    | '/assembleias/$id/preparacao/estrategia'
    | '/assembleias/$id/preparacao/pontos'
    | '/assuntos/$dossieId/documentos/$documentoId'
    | '/dossies/$dossieId/documentos/$documentoId'
    | '/sessoes/$id/documentos/$docId'
    | '/sessoes/$id/preparacao/documentos'
    | '/sessoes/$id/preparacao/documentos-a-criar'
    | '/sessoes/$id/preparacao/estrategia'
    | '/sessoes/$id/preparacao/pontos'
    | '/assembleias/$id/preparacao/documentos-a-criar/$rascunhoId'
    | '/assembleias/$id/preparacao/pontos/$pontoId'
    | '/sessoes/$id/preparacao/documentos-a-criar/$rascunhoId'
    | '/sessoes/$id/preparacao/pontos/$pontoId'
    | '/assembleias/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
    | '/sessoes/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
  id:
    | '__root__'
    | '/_app'
    | '/completar-perfil'
    | '/login'
    | '/_app/agenda'
    | '/_app/base-juridica'
    | '/_app/biblioteca'
    | '/_app/caixa-de-entrada'
    | '/_app/definicoes'
    | '/_app/definicoes-gerais'
    | '/_app/equipa'
    | '/_app/historico'
    | '/_app/integracoes'
    | '/_app/lixeira'
    | '/_app/modelos'
    | '/_app/relatorios'
    | '/_app/'
    | '/_app/assembleias/$id'
    | '/_app/assuntos/$dossieId'
    | '/_app/documentos/$documentoId'
    | '/_app/dossies/$dossieId'
    | '/_app/sessoes/$id'
    | '/_app/assembleias/'
    | '/_app/assuntos/'
    | '/_app/dossies/'
    | '/_app/sessoes/'
    | '/_app/assembleias/$id/preparacao'
    | '/_app/biblioteca/documentos/$docId'
    | '/_app/sessoes/$id/preparacao'
    | '/_app/assuntos/$dossieId/'
    | '/_app/assembleias/$id/documentos/$docId'
    | '/_app/assembleias/$id/preparacao/documentos'
    | '/_app/assembleias/$id/preparacao/documentos-a-criar'
    | '/_app/assembleias/$id/preparacao/estrategia'
    | '/_app/assembleias/$id/preparacao/pontos'
    | '/_app/assuntos/$dossieId/documentos/$documentoId'
    | '/_app/dossies/$dossieId/documentos/$documentoId'
    | '/_app/sessoes/$id/documentos/$docId'
    | '/_app/sessoes/$id/preparacao/documentos'
    | '/_app/sessoes/$id/preparacao/documentos-a-criar'
    | '/_app/sessoes/$id/preparacao/estrategia'
    | '/_app/sessoes/$id/preparacao/pontos'
    | '/_app/assembleias/$id/preparacao/documentos-a-criar/$rascunhoId'
    | '/_app/assembleias/$id/preparacao/pontos/$pontoId'
    | '/_app/sessoes/$id/preparacao/documentos-a-criar/$rascunhoId'
    | '/_app/sessoes/$id/preparacao/pontos/$pontoId'
    | '/_app/assembleias/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
    | '/_app/sessoes/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos': {
      id: '/_app/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AppModelosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lixeira': {
      id: '/_app/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AppLixeiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes': {
      id: '/_app/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipa': {
      id: '/_app/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof AppEquipaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/definicoes-gerais': {
      id: '/_app/definicoes-gerais'
      path: '/definicoes-gerais'
      fullPath: '/definicoes-gerais'
      preLoaderRoute: typeof AppDefinicoesGeraisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/definicoes': {
      id: '/_app/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof AppDefinicoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caixa-de-entrada': {
      id: '/_app/caixa-de-entrada'
      path: '/caixa-de-entrada'
      fullPath: '/caixa-de-entrada'
      preLoaderRoute: typeof AppCaixaDeEntradaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/base-juridica': {
      id: '/_app/base-juridica'
      path: '/base-juridica'
      fullPath: '/base-juridica'
      preLoaderRoute: typeof AppBaseJuridicaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessoes/': {
      id: '/_app/sessoes/'
      path: '/sessoes'
      fullPath: '/sessoes/'
      preLoaderRoute: typeof AppSessoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dossies/': {
      id: '/_app/dossies/'
      path: '/dossies'
      fullPath: '/dossies/'
      preLoaderRoute: typeof AppDossiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assuntos/': {
      id: '/_app/assuntos/'
      path: '/assuntos'
      fullPath: '/assuntos/'
      preLoaderRoute: typeof AppAssuntosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assembleias/': {
      id: '/_app/assembleias/'
      path: '/assembleias'
      fullPath: '/assembleias/'
      preLoaderRoute: typeof AppAssembleiasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessoes/$id': {
      id: '/_app/sessoes/$id'
      path: '/sessoes/$id'
      fullPath: '/sessoes/$id'
      preLoaderRoute: typeof AppSessoesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dossies/$dossieId': {
      id: '/_app/dossies/$dossieId'
      path: '/dossies/$dossieId'
      fullPath: '/dossies/$dossieId'
      preLoaderRoute: typeof AppDossiesDossieIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos/$documentoId': {
      id: '/_app/documentos/$documentoId'
      path: '/documentos/$documentoId'
      fullPath: '/documentos/$documentoId'
      preLoaderRoute: typeof AppDocumentosDocumentoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assuntos/$dossieId': {
      id: '/_app/assuntos/$dossieId'
      path: '/assuntos/$dossieId'
      fullPath: '/assuntos/$dossieId'
      preLoaderRoute: typeof AppAssuntosDossieIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assembleias/$id': {
      id: '/_app/assembleias/$id'
      path: '/assembleias/$id'
      fullPath: '/assembleias/$id'
      preLoaderRoute: typeof AppAssembleiasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assuntos/$dossieId/': {
      id: '/_app/assuntos/$dossieId/'
      path: '/'
      fullPath: '/assuntos/$dossieId/'
      preLoaderRoute: typeof AppAssuntosDossieIdIndexRouteImport
      parentRoute: typeof AppAssuntosDossieIdRoute
    }
    '/_app/sessoes/$id/preparacao': {
      id: '/_app/sessoes/$id/preparacao'
      path: '/preparacao'
      fullPath: '/sessoes/$id/preparacao'
      preLoaderRoute: typeof AppSessoesIdPreparacaoRouteImport
      parentRoute: typeof AppSessoesIdRoute
    }
    '/_app/biblioteca/documentos/$docId': {
      id: '/_app/biblioteca/documentos/$docId'
      path: '/documentos/$docId'
      fullPath: '/biblioteca/documentos/$docId'
      preLoaderRoute: typeof AppBibliotecaDocumentosDocIdRouteImport
      parentRoute: typeof AppBibliotecaRoute
    }
    '/_app/assembleias/$id/preparacao': {
      id: '/_app/assembleias/$id/preparacao'
      path: '/preparacao'
      fullPath: '/assembleias/$id/preparacao'
      preLoaderRoute: typeof AppAssembleiasIdPreparacaoRouteImport
      parentRoute: typeof AppAssembleiasIdRoute
    }
    '/_app/sessoes/$id/preparacao/pontos': {
      id: '/_app/sessoes/$id/preparacao/pontos'
      path: '/pontos'
      fullPath: '/sessoes/$id/preparacao/pontos'
      preLoaderRoute: typeof AppSessoesIdPreparacaoPontosRouteImport
      parentRoute: typeof AppSessoesIdPreparacaoRoute
    }
    '/_app/sessoes/$id/preparacao/estrategia': {
      id: '/_app/sessoes/$id/preparacao/estrategia'
      path: '/estrategia'
      fullPath: '/sessoes/$id/preparacao/estrategia'
      preLoaderRoute: typeof AppSessoesIdPreparacaoEstrategiaRouteImport
      parentRoute: typeof AppSessoesIdPreparacaoRoute
    }
    '/_app/sessoes/$id/preparacao/documentos-a-criar': {
      id: '/_app/sessoes/$id/preparacao/documentos-a-criar'
      path: '/documentos-a-criar'
      fullPath: '/sessoes/$id/preparacao/documentos-a-criar'
      preLoaderRoute: typeof AppSessoesIdPreparacaoDocumentosACriarRouteImport
      parentRoute: typeof AppSessoesIdPreparacaoRoute
    }
    '/_app/sessoes/$id/preparacao/documentos': {
      id: '/_app/sessoes/$id/preparacao/documentos'
      path: '/documentos'
      fullPath: '/sessoes/$id/preparacao/documentos'
      preLoaderRoute: typeof AppSessoesIdPreparacaoDocumentosRouteImport
      parentRoute: typeof AppSessoesIdPreparacaoRoute
    }
    '/_app/sessoes/$id/documentos/$docId': {
      id: '/_app/sessoes/$id/documentos/$docId'
      path: '/documentos/$docId'
      fullPath: '/sessoes/$id/documentos/$docId'
      preLoaderRoute: typeof AppSessoesIdDocumentosDocIdRouteImport
      parentRoute: typeof AppSessoesIdRoute
    }
    '/_app/dossies/$dossieId/documentos/$documentoId': {
      id: '/_app/dossies/$dossieId/documentos/$documentoId'
      path: '/documentos/$documentoId'
      fullPath: '/dossies/$dossieId/documentos/$documentoId'
      preLoaderRoute: typeof AppDossiesDossieIdDocumentosDocumentoIdRouteImport
      parentRoute: typeof AppDossiesDossieIdRoute
    }
    '/_app/assuntos/$dossieId/documentos/$documentoId': {
      id: '/_app/assuntos/$dossieId/documentos/$documentoId'
      path: '/documentos/$documentoId'
      fullPath: '/assuntos/$dossieId/documentos/$documentoId'
      preLoaderRoute: typeof AppAssuntosDossieIdDocumentosDocumentoIdRouteImport
      parentRoute: typeof AppAssuntosDossieIdRoute
    }
    '/_app/assembleias/$id/preparacao/pontos': {
      id: '/_app/assembleias/$id/preparacao/pontos'
      path: '/pontos'
      fullPath: '/assembleias/$id/preparacao/pontos'
      preLoaderRoute: typeof AppAssembleiasIdPreparacaoPontosRouteImport
      parentRoute: typeof AppAssembleiasIdPreparacaoRoute
    }
    '/_app/assembleias/$id/preparacao/estrategia': {
      id: '/_app/assembleias/$id/preparacao/estrategia'
      path: '/estrategia'
      fullPath: '/assembleias/$id/preparacao/estrategia'
      preLoaderRoute: typeof AppAssembleiasIdPreparacaoEstrategiaRouteImport
      parentRoute: typeof AppAssembleiasIdPreparacaoRoute
    }
    '/_app/assembleias/$id/preparacao/documentos-a-criar': {
      id: '/_app/assembleias/$id/preparacao/documentos-a-criar'
      path: '/documentos-a-criar'
      fullPath: '/assembleias/$id/preparacao/documentos-a-criar'
      preLoaderRoute: typeof AppAssembleiasIdPreparacaoDocumentosACriarRouteImport
      parentRoute: typeof AppAssembleiasIdPreparacaoRoute
    }
    '/_app/assembleias/$id/preparacao/documentos': {
      id: '/_app/assembleias/$id/preparacao/documentos'
      path: '/documentos'
      fullPath: '/assembleias/$id/preparacao/documentos'
      preLoaderRoute: typeof AppAssembleiasIdPreparacaoDocumentosRouteImport
      parentRoute: typeof AppAssembleiasIdPreparacaoRoute
    }
    '/_app/assembleias/$id/documentos/$docId': {
      id: '/_app/assembleias/$id/documentos/$docId'
      path: '/documentos/$docId'
      fullPath: '/assembleias/$id/documentos/$docId'
      preLoaderRoute: typeof AppAssembleiasIdDocumentosDocIdRouteImport
      parentRoute: typeof AppAssembleiasIdRoute
    }
    '/_app/sessoes/$id/preparacao/pontos/$pontoId': {
      id: '/_app/sessoes/$id/preparacao/pontos/$pontoId'
      path: '/$pontoId'
      fullPath: '/sessoes/$id/preparacao/pontos/$pontoId'
      preLoaderRoute: typeof AppSessoesIdPreparacaoPontosPontoIdRouteImport
      parentRoute: typeof AppSessoesIdPreparacaoPontosRoute
    }
    '/_app/sessoes/$id/preparacao/documentos-a-criar/$rascunhoId': {
      id: '/_app/sessoes/$id/preparacao/documentos-a-criar/$rascunhoId'
      path: '/$rascunhoId'
      fullPath: '/sessoes/$id/preparacao/documentos-a-criar/$rascunhoId'
      preLoaderRoute: typeof AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRouteImport
      parentRoute: typeof AppSessoesIdPreparacaoDocumentosACriarRoute
    }
    '/_app/assembleias/$id/preparacao/pontos/$pontoId': {
      id: '/_app/assembleias/$id/preparacao/pontos/$pontoId'
      path: '/$pontoId'
      fullPath: '/assembleias/$id/preparacao/pontos/$pontoId'
      preLoaderRoute: typeof AppAssembleiasIdPreparacaoPontosPontoIdRouteImport
      parentRoute: typeof AppAssembleiasIdPreparacaoPontosRoute
    }
    '/_app/assembleias/$id/preparacao/documentos-a-criar/$rascunhoId': {
      id: '/_app/assembleias/$id/preparacao/documentos-a-criar/$rascunhoId'
      path: '/$rascunhoId'
      fullPath: '/assembleias/$id/preparacao/documentos-a-criar/$rascunhoId'
      preLoaderRoute: typeof AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRouteImport
      parentRoute: typeof AppAssembleiasIdPreparacaoDocumentosACriarRoute
    }
    '/_app/sessoes/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId': {
      id: '/_app/sessoes/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
      path: '/rascunhos/$rascunhoId'
      fullPath: '/sessoes/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
      preLoaderRoute: typeof AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRouteImport
      parentRoute: typeof AppSessoesIdPreparacaoPontosPontoIdRoute
    }
    '/_app/assembleias/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId': {
      id: '/_app/assembleias/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
      path: '/rascunhos/$rascunhoId'
      fullPath: '/assembleias/$id/preparacao/pontos/$pontoId/rascunhos/$rascunhoId'
      preLoaderRoute: typeof AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRouteImport
      parentRoute: typeof AppAssembleiasIdPreparacaoPontosPontoIdRoute
    }
  }
}

interface AppBibliotecaRouteChildren {
  AppBibliotecaDocumentosDocIdRoute: typeof AppBibliotecaDocumentosDocIdRoute
}

const AppBibliotecaRouteChildren: AppBibliotecaRouteChildren = {
  AppBibliotecaDocumentosDocIdRoute: AppBibliotecaDocumentosDocIdRoute,
}

const AppBibliotecaRouteWithChildren = AppBibliotecaRoute._addFileChildren(
  AppBibliotecaRouteChildren,
)

interface AppAssembleiasIdPreparacaoDocumentosACriarRouteChildren {
  AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRoute: typeof AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRoute
}

const AppAssembleiasIdPreparacaoDocumentosACriarRouteChildren: AppAssembleiasIdPreparacaoDocumentosACriarRouteChildren =
  {
    AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRoute:
      AppAssembleiasIdPreparacaoDocumentosACriarRascunhoIdRoute,
  }

const AppAssembleiasIdPreparacaoDocumentosACriarRouteWithChildren =
  AppAssembleiasIdPreparacaoDocumentosACriarRoute._addFileChildren(
    AppAssembleiasIdPreparacaoDocumentosACriarRouteChildren,
  )

interface AppAssembleiasIdPreparacaoPontosPontoIdRouteChildren {
  AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute: typeof AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute
}

const AppAssembleiasIdPreparacaoPontosPontoIdRouteChildren: AppAssembleiasIdPreparacaoPontosPontoIdRouteChildren =
  {
    AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute:
      AppAssembleiasIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute,
  }

const AppAssembleiasIdPreparacaoPontosPontoIdRouteWithChildren =
  AppAssembleiasIdPreparacaoPontosPontoIdRoute._addFileChildren(
    AppAssembleiasIdPreparacaoPontosPontoIdRouteChildren,
  )

interface AppAssembleiasIdPreparacaoPontosRouteChildren {
  AppAssembleiasIdPreparacaoPontosPontoIdRoute: typeof AppAssembleiasIdPreparacaoPontosPontoIdRouteWithChildren
}

const AppAssembleiasIdPreparacaoPontosRouteChildren: AppAssembleiasIdPreparacaoPontosRouteChildren =
  {
    AppAssembleiasIdPreparacaoPontosPontoIdRoute:
      AppAssembleiasIdPreparacaoPontosPontoIdRouteWithChildren,
  }

const AppAssembleiasIdPreparacaoPontosRouteWithChildren =
  AppAssembleiasIdPreparacaoPontosRoute._addFileChildren(
    AppAssembleiasIdPreparacaoPontosRouteChildren,
  )

interface AppAssembleiasIdPreparacaoRouteChildren {
  AppAssembleiasIdPreparacaoDocumentosRoute: typeof AppAssembleiasIdPreparacaoDocumentosRoute
  AppAssembleiasIdPreparacaoDocumentosACriarRoute: typeof AppAssembleiasIdPreparacaoDocumentosACriarRouteWithChildren
  AppAssembleiasIdPreparacaoEstrategiaRoute: typeof AppAssembleiasIdPreparacaoEstrategiaRoute
  AppAssembleiasIdPreparacaoPontosRoute: typeof AppAssembleiasIdPreparacaoPontosRouteWithChildren
}

const AppAssembleiasIdPreparacaoRouteChildren: AppAssembleiasIdPreparacaoRouteChildren =
  {
    AppAssembleiasIdPreparacaoDocumentosRoute:
      AppAssembleiasIdPreparacaoDocumentosRoute,
    AppAssembleiasIdPreparacaoDocumentosACriarRoute:
      AppAssembleiasIdPreparacaoDocumentosACriarRouteWithChildren,
    AppAssembleiasIdPreparacaoEstrategiaRoute:
      AppAssembleiasIdPreparacaoEstrategiaRoute,
    AppAssembleiasIdPreparacaoPontosRoute:
      AppAssembleiasIdPreparacaoPontosRouteWithChildren,
  }

const AppAssembleiasIdPreparacaoRouteWithChildren =
  AppAssembleiasIdPreparacaoRoute._addFileChildren(
    AppAssembleiasIdPreparacaoRouteChildren,
  )

interface AppAssembleiasIdRouteChildren {
  AppAssembleiasIdPreparacaoRoute: typeof AppAssembleiasIdPreparacaoRouteWithChildren
  AppAssembleiasIdDocumentosDocIdRoute: typeof AppAssembleiasIdDocumentosDocIdRoute
}

const AppAssembleiasIdRouteChildren: AppAssembleiasIdRouteChildren = {
  AppAssembleiasIdPreparacaoRoute: AppAssembleiasIdPreparacaoRouteWithChildren,
  AppAssembleiasIdDocumentosDocIdRoute: AppAssembleiasIdDocumentosDocIdRoute,
}

const AppAssembleiasIdRouteWithChildren =
  AppAssembleiasIdRoute._addFileChildren(AppAssembleiasIdRouteChildren)

interface AppAssuntosDossieIdRouteChildren {
  AppAssuntosDossieIdIndexRoute: typeof AppAssuntosDossieIdIndexRoute
  AppAssuntosDossieIdDocumentosDocumentoIdRoute: typeof AppAssuntosDossieIdDocumentosDocumentoIdRoute
}

const AppAssuntosDossieIdRouteChildren: AppAssuntosDossieIdRouteChildren = {
  AppAssuntosDossieIdIndexRoute: AppAssuntosDossieIdIndexRoute,
  AppAssuntosDossieIdDocumentosDocumentoIdRoute:
    AppAssuntosDossieIdDocumentosDocumentoIdRoute,
}

const AppAssuntosDossieIdRouteWithChildren =
  AppAssuntosDossieIdRoute._addFileChildren(AppAssuntosDossieIdRouteChildren)

interface AppDossiesDossieIdRouteChildren {
  AppDossiesDossieIdDocumentosDocumentoIdRoute: typeof AppDossiesDossieIdDocumentosDocumentoIdRoute
}

const AppDossiesDossieIdRouteChildren: AppDossiesDossieIdRouteChildren = {
  AppDossiesDossieIdDocumentosDocumentoIdRoute:
    AppDossiesDossieIdDocumentosDocumentoIdRoute,
}

const AppDossiesDossieIdRouteWithChildren =
  AppDossiesDossieIdRoute._addFileChildren(AppDossiesDossieIdRouteChildren)

interface AppSessoesIdPreparacaoDocumentosACriarRouteChildren {
  AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRoute: typeof AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRoute
}

const AppSessoesIdPreparacaoDocumentosACriarRouteChildren: AppSessoesIdPreparacaoDocumentosACriarRouteChildren =
  {
    AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRoute:
      AppSessoesIdPreparacaoDocumentosACriarRascunhoIdRoute,
  }

const AppSessoesIdPreparacaoDocumentosACriarRouteWithChildren =
  AppSessoesIdPreparacaoDocumentosACriarRoute._addFileChildren(
    AppSessoesIdPreparacaoDocumentosACriarRouteChildren,
  )

interface AppSessoesIdPreparacaoPontosPontoIdRouteChildren {
  AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute: typeof AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute
}

const AppSessoesIdPreparacaoPontosPontoIdRouteChildren: AppSessoesIdPreparacaoPontosPontoIdRouteChildren =
  {
    AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute:
      AppSessoesIdPreparacaoPontosPontoIdRascunhosRascunhoIdRoute,
  }

const AppSessoesIdPreparacaoPontosPontoIdRouteWithChildren =
  AppSessoesIdPreparacaoPontosPontoIdRoute._addFileChildren(
    AppSessoesIdPreparacaoPontosPontoIdRouteChildren,
  )

interface AppSessoesIdPreparacaoPontosRouteChildren {
  AppSessoesIdPreparacaoPontosPontoIdRoute: typeof AppSessoesIdPreparacaoPontosPontoIdRouteWithChildren
}

const AppSessoesIdPreparacaoPontosRouteChildren: AppSessoesIdPreparacaoPontosRouteChildren =
  {
    AppSessoesIdPreparacaoPontosPontoIdRoute:
      AppSessoesIdPreparacaoPontosPontoIdRouteWithChildren,
  }

const AppSessoesIdPreparacaoPontosRouteWithChildren =
  AppSessoesIdPreparacaoPontosRoute._addFileChildren(
    AppSessoesIdPreparacaoPontosRouteChildren,
  )

interface AppSessoesIdPreparacaoRouteChildren {
  AppSessoesIdPreparacaoDocumentosRoute: typeof AppSessoesIdPreparacaoDocumentosRoute
  AppSessoesIdPreparacaoDocumentosACriarRoute: typeof AppSessoesIdPreparacaoDocumentosACriarRouteWithChildren
  AppSessoesIdPreparacaoEstrategiaRoute: typeof AppSessoesIdPreparacaoEstrategiaRoute
  AppSessoesIdPreparacaoPontosRoute: typeof AppSessoesIdPreparacaoPontosRouteWithChildren
}

const AppSessoesIdPreparacaoRouteChildren: AppSessoesIdPreparacaoRouteChildren =
  {
    AppSessoesIdPreparacaoDocumentosRoute:
      AppSessoesIdPreparacaoDocumentosRoute,
    AppSessoesIdPreparacaoDocumentosACriarRoute:
      AppSessoesIdPreparacaoDocumentosACriarRouteWithChildren,
    AppSessoesIdPreparacaoEstrategiaRoute:
      AppSessoesIdPreparacaoEstrategiaRoute,
    AppSessoesIdPreparacaoPontosRoute:
      AppSessoesIdPreparacaoPontosRouteWithChildren,
  }

const AppSessoesIdPreparacaoRouteWithChildren =
  AppSessoesIdPreparacaoRoute._addFileChildren(
    AppSessoesIdPreparacaoRouteChildren,
  )

interface AppSessoesIdRouteChildren {
  AppSessoesIdPreparacaoRoute: typeof AppSessoesIdPreparacaoRouteWithChildren
  AppSessoesIdDocumentosDocIdRoute: typeof AppSessoesIdDocumentosDocIdRoute
}

const AppSessoesIdRouteChildren: AppSessoesIdRouteChildren = {
  AppSessoesIdPreparacaoRoute: AppSessoesIdPreparacaoRouteWithChildren,
  AppSessoesIdDocumentosDocIdRoute: AppSessoesIdDocumentosDocIdRoute,
}

const AppSessoesIdRouteWithChildren = AppSessoesIdRoute._addFileChildren(
  AppSessoesIdRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppBaseJuridicaRoute: typeof AppBaseJuridicaRoute
  AppBibliotecaRoute: typeof AppBibliotecaRouteWithChildren
  AppCaixaDeEntradaRoute: typeof AppCaixaDeEntradaRoute
  AppDefinicoesRoute: typeof AppDefinicoesRoute
  AppDefinicoesGeraisRoute: typeof AppDefinicoesGeraisRoute
  AppEquipaRoute: typeof AppEquipaRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppLixeiraRoute: typeof AppLixeiraRoute
  AppModelosRoute: typeof AppModelosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssembleiasIdRoute: typeof AppAssembleiasIdRouteWithChildren
  AppAssuntosDossieIdRoute: typeof AppAssuntosDossieIdRouteWithChildren
  AppDocumentosDocumentoIdRoute: typeof AppDocumentosDocumentoIdRoute
  AppDossiesDossieIdRoute: typeof AppDossiesDossieIdRouteWithChildren
  AppSessoesIdRoute: typeof AppSessoesIdRouteWithChildren
  AppAssembleiasIndexRoute: typeof AppAssembleiasIndexRoute
  AppAssuntosIndexRoute: typeof AppAssuntosIndexRoute
  AppDossiesIndexRoute: typeof AppDossiesIndexRoute
  AppSessoesIndexRoute: typeof AppSessoesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppBaseJuridicaRoute: AppBaseJuridicaRoute,
  AppBibliotecaRoute: AppBibliotecaRouteWithChildren,
  AppCaixaDeEntradaRoute: AppCaixaDeEntradaRoute,
  AppDefinicoesRoute: AppDefinicoesRoute,
  AppDefinicoesGeraisRoute: AppDefinicoesGeraisRoute,
  AppEquipaRoute: AppEquipaRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppLixeiraRoute: AppLixeiraRoute,
  AppModelosRoute: AppModelosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssembleiasIdRoute: AppAssembleiasIdRouteWithChildren,
  AppAssuntosDossieIdRoute: AppAssuntosDossieIdRouteWithChildren,
  AppDocumentosDocumentoIdRoute: AppDocumentosDocumentoIdRoute,
  AppDossiesDossieIdRoute: AppDossiesDossieIdRouteWithChildren,
  AppSessoesIdRoute: AppSessoesIdRouteWithChildren,
  AppAssembleiasIndexRoute: AppAssembleiasIndexRoute,
  AppAssuntosIndexRoute: AppAssuntosIndexRoute,
  AppDossiesIndexRoute: AppDossiesIndexRoute,
  AppSessoesIndexRoute: AppSessoesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CompletarPerfilRoute: CompletarPerfilRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
